### PR TITLE
ci: merge staging to master

### PR DESCRIPTION
**Pull request by maxwell-aiden**
This is an automatic PR generated by the pipeline CI/CD. This will be automatically fast-forward merged if successful.

### CODE REVIEW

**Comment by CMCDragonkai** [comment]
@tegefaulkes this isn't the correct way to release from a separate branch.

The 1.1.3 wasn't pushed onto github? You're supposed to push up the tag commit?

Furthermore the reason the windows job broke is due to nodejs not being installed. Not due to anything about artifacts, just read above. You should get used to scanning the logs a bit.

**Comment by CMCDragonkai** [comment]
```
Chocolatey v2.2.2
Installing the following packages:
nodejs.install
By installing, you accept licenses for the packages.
[NuGet] One or more unresolved package dependency constraints detected in the Chocolatey lib folder. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'nodejs 12.10.0 constraint: nodejs.install (= 12.10.0)'
Unable to resolve dependency: Unable to resolve dependencies. 'nodejs.install 18.15.0' is not compatible with 'nodejs 12.10.0 constraint: nodejs.install (= 12.10.0)'.
Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Failures
 - nodejs.install - Unable to resolve dependency: Unable to resolve dependencies. 'nodejs.install 18.15.0' is not compatible with 'nodejs 12.10.0 constraint: nodejs.install (= 12.10.0)'.
    Directory: C:\GitLab-Runner\builds\MatrixAI\open-source\js-timer\tmp\chocolatey
Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
d-----        11/7/2023   1:[58](https://gitlab.com/MatrixAI/open-source/js-timer/-/jobs/5473109155#L58) AM                nodejs.install                                                        
Chocolatey v2.2.2
Attempting to build package from 'nodejs.install.nuspec'.
```

Can you push up your 1.1.3 tag?

**Comment by CMCDragonkai** [comment]
Also rather than using a branch like `feature-eager-cancellation` just create something like `cjs` branch and release from there.

**Comment by CMCDragonkai** [comment]
image

No 1.1.2 nor 1.1.3.

**Comment by CMCDragonkai** [comment]
This pipeline was skipped. I'm adding a new commit so that the CI runs again. Also sometimes try clearing the pipeline cache.

**Comment by tegefaulkes** [comment]
Sorry, I thought I did. I'll have to do it when I'm in the office on friday.

**Pull request merged**
